fauna/query_builder.py
We made a sigil change from `$` to `${}` for cross-driver consistency, but left some docstrings describing a `$`-sigil.
Update the docstrings.
=> Update docstrings for  sigil

fauna/models.py
BT-3634
We have a coming wire protocol change that will wrap documents in a `@doc` tag.
Propose a model that should require minimal changes to the current contract once incorporated into the encoding/decoding.
Describe the manual and automated tests you completed to verify the change is working as expected.
=> Add a DocumentDict model for @doc protocol change

fauna/__init__.py, fauna/models.py, fauna/wire_protocol.py, tests/integration/test_data_type_roundtrips.py, tests/unit/conftest.py, tests/unit/test_models.py, tests/unit/test_wire_protocol.py
Protocol changes must be handled:
New @doc, @ref, and @set tag. The @doc and @ref tags are used for documents. @doc is used when we have read a document, and @ref is used if we have not read the document.
@set will wrap a page cursor, like so:
```
{
"@set": {
"data": [ ... ],
"after": "ABCD",
}
}
```
A document with the field "name": "Foo" will look like this:
```
"@doc": {
"id": "1234",
"coll": { "@mod": "User" },
"ts": { "@time": "..." },
"name": "Foo",
}
```
After running User.byId("1234").delete(), the response will be:
```
"@ref": {
"id": "1234",
"coll": { "@mod": "User" },
}
```
If you stored a reference to another document, it will use the @ref tag:
```
"@doc": {
"id": "1234567",
"coll": { "@mod": "User" },
"ts": { "@time": "..." },
"books": [
"@ref": {
"id": "55",
"coll": { …
```
=> Support protocol changes

fauna/client.py, fauna/headers.py, tests/unit/conftest.py, tests/unit/test_client.py
We need to expose an option to enable or disable typechecking at the Client and the Query. The default should be that x-typecheck is unset.
* Add a typecheck arg to the Client used to set the correct header
* Add a typecheck arg to QueryOptions used to set the correct header
* Some misc cleanup 
Extended unit tests.
=> Add support for typecheck

fauna/client.py, fauna/errors.py, fauna/response.py, tests/integration/test_query.py, tests/unit/test_client.py
We don't support constraint_failures from the QueryFailure wire protocol.
Error handling probably deserves more love soon, but I think this is an improvment.
* Add support for constraint_failures. For now, added ConstraintFailure dataclass to errors.py file, although the wire_protocol.py should be renamed to encoding.py and we should probably encapsulate wire wire protocol concepts in a wire protocol file..
* Separates protocol error handling from the rest for the moment and be strict with query success and failure
* Sneak in a quick stats contract update
* Add a few unit tests
* Add an integ test for the constraint failures
Added new unit tests and a new integ test
=> Add support for constraint failures

fauna/__init__.py, fauna/client.py, fauna/query_builder.py, fauna/wire_protocol.py, tests/integration/conftest.py, tests/unit/test_query_builder.py, tests/unit/test_wire_protocol.py
In the throws of rapid development, query building and encoding were coupled.
Decouple them by embedding the encoding protocol for a query builder in the encoding module rather than letting the builder encode itself and take a dependency on the encoder.
* Updated unit tests
=> Decouple encoding from query building

README.rst
Ticket(s): BT-3618
```
$ python3 -m twine check dist/*
Checking dist/fauna-10.0.0-py3-none-any.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be rendered on PyPI.
line 40: Warning: Title underline too short.
Example Usage
-----------
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.
Checking dist/fauna-10.0.0.tar.gz: FAILED
```
A few formatting tweaks to make twine (reStructuredText) happy
I was able to publish a test package
☝️
=> Updated README formatting

.gitignore, fauna/http/http_client.py, setup.py
When testing against Vercel functions I ran into:
```
ModuleNotFoundError: No module named 'fauna.http'
```
- Added `fauna.http` to packages in `setup.py`
- Removed unused imports
- Updated `.gitignore`
http submodule is included in bundled module
I'm at least getting a 403 now at Vercel until my new test account user is added to the beta access list 😉
=> Fixups for http client rename

fauna/query_builder.py, tests/unit/test_query_builder.py
We don't have a str repr for a Query Interpolation.
Add a str repr to help users preview the full query in the simplest manner possible.
Added str checks to a couple tests.
=> Add __str__ to Query Interpolation

tests/run-tests.sh
We can't invoke python inside make inside the pipeline.
Instead of troubleshooting this now, just call coverage/pytest directly.
=> Run pytest commands directly inside pipeline

concourse/pipeline.yml
We should use FAUNA_ENDPOINT rather than the deconstructed env vars.
Build FAUNA_ENDPOINT inside the pipeline
=> Use FAUNA_ENDPOINT in the pipeline

tests/run-tests.sh
We're running the integration tests in the pipeline before faunadb is ready.
Ping/sleep until we're ready.
`make docker-test`
=> Ping faunadb until it's ready

README.rst
The readme is missing details on configuring the client.
* Add the most critical configuration guidance, `secret` and `endpoint`. The rest can be found by looking at the init signature.
* Fix a few grammar issues.
N/A
----
=> Add secret and endpoint config to readme

fauna/client/client.py
Ticket(s): BT-3676
We have a left over print statement in `Client.__init__` 
Remove it
----
=> Remove print() statement in client init

fauna/client/client.py, tests/unit/test_client.py
Ticket(s): BT-3681
We don't check the query argument type at runtime. This can result in confusing error messages.
Check that the type of `fql` arg is `QueryInterpolation`.
Added test
----
=> Check query arg type and raise

fauna/client/client.py, fauna/client/wire_protocol.py, fauna/encoding/encoder.py, fauna/query/models.py, tests/unit/test_models.py, tests/unit/test_wire_protocol.py
Ticket(s): BT-3677
The models to represent the query response/info and documents, refs, and modules lack a `__repr__` implementation. This makes it difficult to developers to easily print their object.
* Implement `__repr__` for each custom class
* Revised QuerySuccess with stronger contract
* Added a few missing docstrings
* Removed a few `__str__` implementations. These require a bit more thought
Added new tests and ran `make docker-test`
----
=> Add __repr__ to models

tests/integration/test_query.py
Testing an explicit value on the contention retries stat causes the tests to be flaky
Just test that it has a value
Fixes flaky test runs
Ran the test suite locally multiple times with docker compose
----
=> Only test contention retries exists

fauna/http/httpx_client.py, tests/integration/test_client.py
Ticket(s): BT-3679
We were emitting a JSON error when we receive invalid JSON instead of a Client error.
Try/Except
New integ test.
----
=> Emit client error instead of json error

fauna/client/client.py
Ticket(s): BT-###, FE-###,...
I noticed there were a number of query_check_codes which were outdated/no longer used. The only one now which is a query check error is "invalid_query".
----
=> Remove outdated query_check_codes

Makefile, tests/run-tests.sh
Ticket(s): BT-###, FE-###,...
Some diffs are truncated when they fail during testing.
Add -v flag to pytest
Clearer test results
make docker-test
----
=> Run tests with -v flag

requirements.txt, setup.py
The integ tests in a container were taking forever to setup because of loose dependency requirements.
Peg deps to specific versions.
Container spins up much faster
make docker-test
----
=> Strict version requirements for deps

concourse/scripts/build.sh, tests/run-tests.sh
I suspect that the pypi object store migration revealed that we're using an unusual or deprecated package? Anyway, codecov is no longer found, and the documentation says we shoudl be using coverage.
Update codecov to coverage
It works again.
make docker-test
----
=> Use coverage not codecov

README.rst, fauna/client/client.py, fauna/errors/__init__.py, fauna/errors/errors.py, tests/integration/test_query.py, tests/unit/test_client.py
BT-3714
We need AbortError and InvalidRequestError, and nested query info feels wrong.
* For abort handling, we need to decode abort. Instead of decoding just data, decode the entire body after the protocol check. This allows the success/failure cases to access decoded body without worrying about it.
* Move QueryInfo props to the top-level of ServiceError with multiple inheritance
* Remove FaunaError inheritance from ProtocolError. It's not really a FaunaError, or at least it probably isn't.
Unit and integ tests pass
----
=> Abort, InvalidRequest, and top-level info

concourse/pipeline.yml
We need to use a different key to get at testttools
----
=> Use a diff key for testtools

fauna/client/client.py, tests/integration/test_query.py
Evaluate implies that we've sent the query to Fauna, but we've just failed to encode.
Use "encode" instead of "evaluate" in error message.
Describe the manual and automated tests you completed to verify the change is working as expected.
----
=> Improve client encoding error message

fauna/__init__.py, fauna/encoding/decoder.py, fauna/encoding/encoder.py, fauna/query/__init__.py, fauna/query/models.py, tests/integration/test_query.py, tests/unit/test_encoding.py
We introduced a Null Document for scenarios when the document may not exist. This needs explicit support in drivers.
* Add NullDocument class that accepts a DocumentReference and NamedDocumentReference. I opted for this to avoid a NullDocumentReference and NullNamedDocumentReference.
* Decode @ref where exists == false into NullDocument
* Encodes into a @ref that excludes the exists and cause properties
Added unit and integ tests
----
=> Add support for null doc

fauna/client/client.py, fauna/client/headers.py, tests/integration/test_paginate.py, tests/integration/test_query.py, tests/unit/test_client.py
Ticket(s): BT-3938
- we set `x-timeout-ms` instead of `x-query-timeout-ms`
- we send the header as a float, e.g. `5000.0` instead of `5000`
Update the header and header encoding.
Query timeouts are enforced correctly.
Added a test that`QueryTimeoutError`s get raised when queries run beyond the specified `query_timeout` configuration.
Added a test for `Client.paginate` that uses query timeouts to demonstrate that options are getting passed down to requests.
----
=> Fix query timeout

.github/workflows/yapf.yml, README.rst, fauna/__init__.py, fauna/client/client.py, setup.py, tests/integration/test_client.py, tests/integration/test_query.py
Ticket(s): BT-3997
fixes #126 
When the `query_timeout` option is provided to the client configuration, the `X-Query-Timeout-Ms` header gets encoded as a decimal. e.g. "5000.0" instead of "5000". Fauna returns a 400 error when this happens.
Make sure that the header is encoded as an integer.
We did this for when the query timeout is configured in QueryOptions (see #124), but we didn't cover the client config path.
Add test coverage for configuring and actually sending a request.
Clients can be configured with query_timeout and Fauna will respect it.
Added a test to actually send requests with a client configured with query_timeout. One request with client config and one request with no client config but with QueryOptions.
----
By submitting this pull request, I confirm that you can use, …
=> Encode Query timeout header correctly

fauna/client/client.py, tests/unit/test_client.py
Ticket(s): BT-3922
1) Consumers are unable to specify their own timeout settings
2) We should be setting a default Query Timeout & Client Buffer Timeout
- Timeouts can optionally be set when initializing a new client
- Set defaults for Query and Client Buffer Timeouts
- Improved defaults
- Consumers can override settings as desired
Basic local testing
----
=> Updated timeouts

concourse/scripts/publish_docs.sh
[pdoc3](https://pypi.org/project/pdoc3/) isn't maintained anymore
Use [pdoc](https://pypi.org/project/pdoc/)
Just a visual spot check, the output looks better
Ran `python -m pdoc ./fauna -o docs` locally and did a basic spot check of the output
----
=> Use pdoc for generated docs

fauna/client/client.py, fauna/encoding/wire_protocol.py, fauna/errors/errors.py, tests/integration/test_query.py, tests/unit/test_wire_protocol.py
Ticket(s): BT-4059
Driver needs to be updated to support Schema Version which is now part of the query response. 
Add Schema Version
The schema version used by the query. This can be used by clients displaying schema to determine when they should refresh their schema. If the schema version that a client has stored differs from the one returned by the query, schema should be refreshed.
Additional test included
----
=> Add Schema Version

fauna/client/client.py, fauna/errors/__init__.py, fauna/errors/errors.py
Ticket(s): BT-3657
Not currently mapping Contended Transaction Errors 
Add `ContendedTransactionError` type
Proper type for the error
None - I didn't add a test since it would require that we simulate concurrent operations within the test which I figured could be flakey.
----
=> Support Contended Transaction Errors

concourse/scripts/publish_docs.sh
Ticket(s): BT-4066
```
sed: can't read ./docs/index.html: No such file or directory
```
pdoc has a different output structure
Copy the contents `docs/` 
Files are published as expected
https://fauna.github.io/fauna-python/0.8.0/fauna/client/client.html -- built in a local docker image and published manually since the pipeline failed
----
=> Pydoc publishing

fauna/client/client.py, fauna/http/http_client.py, fauna/http/httpx_client.py
Ticket(s): BT-3723
Customers need a way to gracefully close connections to Fauna.
Provide a close method on the Fauna client and underlying HTTP clients. If the Fauna Client is using the global http client, the global client is closed and set to None to prevent use of a closed client.
Clients can be closed.
----
=> provide a way to close the http client

README.rst
Ticket(s): BT-3848
Add documentation for the timeouts available on the client and query.
----
=> add documentation for timeouts

fauna/http/httpx_client.py
Ticket(s): BT-3908
There are environments where a client may see a transport error that is safe to retry.
Handle the retry internally up to a limit (3).
Transient transport errors are automatically handled in the client.
----
=> retry on transport errors

README.rst, fauna/__init__.py
Ticket: BT-4104
- Update README for v10 GA launch
- Bump version to 1.0.0 for v10 GA launch
=> v10 GA Launch (1.0.0)

README.rst, fauna/client/client.py, fauna/client/retryable.py, fauna/encoding/wire_protocol.py, fauna/errors/__init__.py, fauna/errors/errors.py, fauna/http/http_client.py, fauna/http/httpx_client.py, tests/unit/test_retryable.py, tests/unit/test_wire_protocol.py
Ticket(s): BT-3465
ThrottlingError is very retryable, but we don't currently retry.
* Implement a basic exponential backoff retry strategy for ThrottlingError.
* Expose RetryPolicy configuration at the client level
* Default the RetryPolicy to 3 max attempts and a maximum backoff of 20 seconds
Added unit tests. Existing integ tests pass.
----
=> Add retry config for 429/502 errors

README.rst, fauna/client/client.py, fauna/client/retryable.py, fauna/errors/__init__.py, fauna/errors/errors.py, tests/unit/test_retryable.py
Ticket(s): BT-3465
After some discussion, we're opting to retry only on 429 for now.
* Remove retries on 502s.
* Flatten retry config because it felt inconsistent as is. We can revisit the config story for the driver on a future major release
updated tests
----
=> Do not retry on 502

concourse/pipeline.yml, concourse/tasks/query-limits-tests.yml, tests/docker-compose-limits-tests.yml, tests/integration/test_client_with_query_limits.py, tests/run-query-limits-tests.sh
Ticket(s): BT-4181
We don't currently have integration test coverage of the query-limit and throttling behavior.
Add a test case that runs against a specially-configured database with query limits and validate that the queries that are throttled succeed on the Client retry logic (`stats.attempts > 1`).
Dependent on the files merged in this PR: https://github.com/fauna/testtools/pull/86
New test case added and running in pipeline.
Ran the test locally using the multiple docker-compose files; will need to validate in the pipeline that the Concourse collateral is setup correctly, but I was mostly able to copy what works in the JS driver after some iterations there.
----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
=> BT-4181: Add query limits integration test and add to pipeline

fauna/encoding/encoder.py, tests/unit/test_encoding.py
https://github.com/fauna/fauna-python/issues/154
We weren't tracking circular references properly.
Use a list to track references and append/pop appropriately. Marker lookup could be made more efficient with a more appropriate data structure, but for now this fixes the bug.
=> Only detect circular refs when they're circular

.github/workflows/build_and_test.yml, docker/Dockerfile, docker/docker-compose.yml, docker/feature-flags.json, fauna/client/__init__.py, fauna/client/client.py, fauna/client/retryable.py, fauna/encoding/decoder.py, fauna/encoding/encoder.py, fauna/errors/__init__.py, fauna/errors/errors.py, fauna/http/http_client.py, fauna/http/httpx_client.py, fauna/query/models.py, tests/integration/conftest.py, tests/integration/test_client_with_query_limits.py, tests/integration/test_stream.py, tests/unit/test_client.py, tests/unit/test_encoding.py, tests/unit/test_httpx_client.py
ENG-6011, ENG-6012, ENG-6013, ENG-6014, ENG-6039
With this PR we are already able to support the following snippet of code:
```
from fauna import fql
from fauna.client import Client
client = Client(endpoint = "http://localhost:8443", secret = "secret")
token = client.query(fql('Products.all().toStream()'))
with client.stream(token.data) as stream:
for evt in stream:
print(evt)
if some_condition:
stream.close()
```
=> Initial work to support streams

fauna/client/client.py, tests/integration/test_stream.py
=> allow providing stream start ts

.github/workflows/validate-readme.yml, README.md, setup.py
This pr will have 2 commits:
1. move from .rst to .md - github seems to be struggling to render the .rst file and I don't see a reason to keep it that way when pypi is compatible with both: https://github.com/fauna/fauna-python
2. add a section for the streaming docs
You can see what the updated README looks like here:
https://github.com/fauna/fauna-python/tree/streaming-docs
----
=> add streaming section

requirements.txt, setup.py
We observed a significant performance issue when making request with this driver. We identified the root cause as a dependency with a misconfigured socket in the version we were using. 
They have since patched it: https://github.com/encode/httpcore/pull/651
Upgrade dependencies solves the performance issue.
We profiled the Client before and after upgrade and observed a 50ms ssl socket read drop to 6ms. 
----
=> Upgrade dependencies

requirements.txt, setup.py
We observed a significant performance issue when making request with this driver. We identified the root cause as a dependency with a misconfigured socket in the version we were using. 
They have since patched it: https://github.com/encode/httpcore/pull/651
Upgrade dependencies solves the performance issue.
We profiled the Client before and after upgrade and observed a 50ms ssl socket read drop to 6ms. 
----
=> Merge upgrade dependencies

README.rst
Ticket(s): https://faunadb.atlassian.net/browse/DOCS-2618
The current README indicates streaming isn't implemented, but it is available in the beta driver.
Update the README to include information about Event Streaming support in Beta. Also fixes a few grammar issues.
----
=> [DOCS-2618] Note that event streaming is supported in beta

concourse/pipeline.yml
Vercel made some changes that have broken a platform test.
I was able to get the vercel project to update and run after manually adjusting project settings–and therefore proved the platform test is not broken by this change–but it will take a bit more work to encode properly.
For now, remove this test and the flakey throttling test so we can release.
manual
----
=> Remove vercel and limits test in pipeline

README.md
Ticket(s): [DOCS-2647](https://faunadb.atlassian.net/browse/DOCS-2647)
The `<stream>.close()` method for Event Streaming is undocumented.
Documents the method.
----
[DOCS-2647]: https://faunadb.atlassian.net/browse/DOCS-2647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-2647] Document `<stream>.close()` method

README.rst
Ticket(s): [DOCS-2635)](https://faunadb.atlassian.net/browse/DOCS-2635)
We don't currently document the `Client.paginate()` method.
Add documentation to the README.
----
=> [DOCS-2635] Document `Client.paginate()`

README.md
Ticket(s): [DOCS-2789](https://faunadb.atlassian.net/browse/DOCS-2789)
The README contains a few malformed links (carried over from RST).
Fixes them. Also adds proper headings for subsections.
----
[DOCS-2789]: https://faunadb.atlassian.net/browse/DOCS-2789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-2789] Fix malformed links in Python README

concourse/pipeline.yml
We no longer want to release beta versions of the driver. Instead, we'll likely gate beta features via configuration.
Remove it from the pipeline.
None
----
=> Remove beta release steps

README.md
Ticket(s): [DOCS-2823](https://faunadb.atlassian.net/browse/DOCS-2823)
Removes class names from method references in text. This aligns with Google's [style recommendations](https://developers.google.com/style/code-in-text#method-names).
----
[DOCS-2823]: https://faunadb.atlassian.net/browse/DOCS-2823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-2823] README: Remove class names in method refs

README.md, concourse/scripts/publish_docs.sh
Ticket(s): [DOCS-3241](https://faunadb.atlassian.net/browse/DOCS-3241)
- We don't link to the driver API reference from the README. Users may not be aware these docs exist.
- I recently added a `latest/` symlink to the `gh-pages` branch that points to the latest release of the API ref. However, that symlink isn't updated as part of the release process.
- Link to the API ref in the README.
- Update the `latest/` symlink in the `gh-pages` branch as part of release.
----
[DOCS-3241]: https://faunadb.atlassian.net/browse/DOCS-3241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-3220] Cross-link to driver API reference

.github/workflows/build_and_test.yml, fauna/client/client.py, fauna/http/httpx_client.py
* Force HTTPX Client to use HTTP 1.1
* Do not automatically retry transport errors
Regarding HTTP 1.1., the [h2 library has a bug](https://github.com/python-hyper/h2/issues/1181) that mishandles the HTTP2 protocol for GOAWAY frames. When it receives a GOAWAY, in progress streams are not allowed to complete. This means any time our edge issues a GOAWAY an in progress request will throw even if Fauna handled it correctly.
The automatic retry was causing the client to resend the query. This is an unsafe retry because the client doesn't know whether Fauna ran the query.
* Our edge issues a GOAWAY consistently at 10000 requests. We observed this behavior with HTTP/2 enabled and not when disabled.
* - [X] Bug fix (non-breaking change that fixes an issue)
* - [ ] New feature (non-breaking change …
=> Only use http1.1

tests/integration/test_stream.py
Remove sleeps from streaming tests.
Sleeps were added to patch over a long fixed bug. Time coordination should not be necessary and failures should be investigated further.
Unit tests changed ran many times locally without failures.
NA
----
=> Remove sleeps from streaming tests

tests/integration/test_stream.py
Enable testing streaming status event.
Status event is available for testing now.
Existing unit test re-enabled.
NA
----
=> Enable testing status event

README.md, docker/docker-compose.yml, docker/feature-flags.json, fauna/client/__init__.py, fauna/client/client.py, tests/docker-compose-tests.yml, tests/integration/test_change_feeds.py
Add changefeeds support to the Python driver.
Changefeeds allows to interactively poll from a stream instead of having it open at all times. It's useful for cron jobs and other forms of periodic tasks to sync 3rd party systems.
Unit tests are included.
NA
* - [X] New feature (non-breaking change that adds functionality)
* - [X] My change requires a change to Fauna documentation.
* - [X] My change requires a change to the README, and I have updated it accordingly.
----
=> ENG-6679: Introduce support for changefeeds

fauna/client/client.py, tests/integration/test_change_feeds.py, tests/integration/test_stream.py
[FE-5985](https://faunadb.atlassian.net/browse/FE-5985)
Added additional input validation for `StreamIterator` and `ChangeFeedIterator` constructors: raise an error if both `cursor` and `start_ts` are provided as options.
We currently allow both start_ts and cursor options to be provided at the same time for Streams and ChangeFeeds. When that happens, `cursor` is used and `start_ts` is silently ignored. We should raise an error instead.
This is a follow up to a previous discussion: https://github.com/fauna/fauna-python/pull/192#discussion_r1766983360
Additional integration tests were added to confirm an error is raised.
* - [x] Breaking change (backwards-incompatible …
=> [FE-5985] Error when configuring start_ts and cursor at the same time

README.md, fauna/client/client.py
Renames `Changed Feeds` to `Event Feeds` in the README and comments.
* Renames `Changed Feeds` to `Event Feeds` in the README and comments.
* Move the `Change Feeds` section before the `Event Streaming` section in the README (per Product request)
I'll merge this PR at the same time as documentation changes go live.
Align with our documentation and marketing
N/A
* - [ ] My code follows the code style of this project.
* - [x] My change requires a change to Fauna documentation.
* - [x] My change requires a change to the README, and I have updated it accordingly.
----
By submitting this pull request, I …
=> docs: [DOCS-3549] Rename Change Feeds to Event Feeds

README.md, fauna/client/__init__.py, fauna/client/client.py, fauna/encoding/decoder.py, fauna/encoding/encoder.py, fauna/query/__init__.py, fauna/query/models.py, tests/integration/test_change_feeds.py, tests/integration/test_feeds.py, tests/integration/test_stream.py, tests/unit/test_client.py, tests/unit/test_encoding.py, tests/unit/test_models.py
This patch renames CDC terms according to our new guidelines.
* "Steam token" becomes "Event source"
* `.change_feed(..)` becomes `.feed(..)`
* `ChangeFeed{Options,Iterator,Page}` becomes `Feed{Options,Iterator,Page}`
Old terms related to streaming are deprecated and should be removed in the next major version. Old terms related to event feeds were ripped off.
Unit tests included.
NA.
* - [X] New feature (non-breaking change that adds functionality)
* - [X] My change requires a change to Fauna documentation.
* - [X] My change requires a change to the README, and I have updated it accordingly.
----
By submitting …
=> Rename CDC terms

README.md, fauna/client/client.py, fauna/http/httpx_client.py, tests/integration/test_stream.py
* Adds debugging logging using standard logging package
* Raw requests including body, but excluding the Authorization header are logged
* Raw responses are logged
Enable debug logging with:
```python
import logging
from fauna.client import Client
from fauna import fql
logging.basicConfig(
level=logging.DEBUG
)
c = Client()
c.query(fql("42"))
```
BT-5156
When users encounter unexpected behaviors they may need to inspect raw headers and data.
Why not a special env var named FAUNA_DEBUG? While we're doing this in other languages, it breaks a standard within Python that is intended to be configurable by logging namespace. Following the standard enables library consumers maximum control over logging within their applications without special treatment.
`httpcore` and `httpx` debug logs are …
=> feat: add debug logging

README.md
* Updates several doc links
* Fixes a minor typo
* Adds some more context to Event Streaming so it better aligns with Event Feeds.
We recently updated the doc URLs for CDC features (Event Streaming and Event Feeds). While the previous links still work, this helps users avoid a hop.
The other changes are non-substantial wording changes.
N/A
* - [ ] My code follows the code style of this project.
* - [x] My change requires a change to Fauna documentation.
* - [x] My change requires a change to the README, and I have updated it accordingly.
----
By submitting this pull request, I confirm that you can use, …
=> docs: Update CDC links in README

Makefile, requirements.txt, setup.py, tests/unit/test_client.py
Update `setup.py` with the desired `httpx` versions
#206 didn't include updating the `setup.py` 🤦‍♂️ 
N/A
* - [x] Bug fix (non-breaking change that fixes an issue)
* - [x] My code follows the code style of this project.
----
=> fix: Bump httpx in setup.py

fauna/query/models.py
Fix for `pdoc` generator
```
File "/usr/local/lib/python3.9/site-packages/pdoc/templates/default/module.html.jinja2", line 46, in block 'nav_submodules'
{% if module.submodules %}
File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 487, in getattr
return getattr(obj, attribute)
File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
val = self.func(instance)
File "/usr/local/lib/python3.9/site-packages/pdoc/doc.py", line 478, in submodules
for mod_name, mod in extract.iter_modules2(self.obj).items():
File "/usr/local/lib/python3.9/site-packages/pdoc/extract.py", line 256, in iter_modules2
members = dir(module) if mod_all is None else mod_all
File "/tmp/build/1a4543b4/fauna-python-repository/./fauna/query/models.py", line 20, in __dir__
return …
```
=> fix: pdoc failure
