fauna/fauna-python

- fauna/client.py
Two quick touch ups that I found when validating drivers:
- weird formatting 
- removed TODO was that was done
> Quick YAPF fix and TODO cleanup

- README.rst
Ticket(s): BT-3625
Need to notify users about the current beta status of this driver.
Add note to top of README
> Add beta details to README

- .github/PULL_REQUEST_TEMPLATE.md
Ticket(s): FE-3287
When customers submit pull requests to this repo, they must agree to our terms of reuse.
Update PR template to clarify rights.
> Add terms to PR template

- README.rst
Ticket(s): BT-3675
Readme examples aren't quite copy-pastable.
Clean them up so they will run without any adjustments.
Copy/pasted into new project to test.
----
> Make readme examples copy-pastable

- README.rst
- fauna/client/endpoints.py
- fauna/client/utils.py
- tests/unit/test_client.py
* We aligned on Endpoints.Default and to remove Preview for the moment.
* Make these changes
`make docker-test`
----
> Change to Endpoints.Default

- fauna/client/client.py
- fauna/encoding/encoder.py
- fauna/query/__init__.py
- fauna/query/query_builder.py
- tests/integration/conftest.py
- tests/unit/test_client.py
- tests/unit/test_query_builder.py
We've decided on Query
Rename QueryInterpolation to Query
`make docker-test`
----
> Rename QueryInterpolation to Query

- README.rst
- fauna/client/__init__.py
- fauna/client/client.py
- fauna/client/wire_protocol.py
- tests/integration/test_query.py
- tests/unit/test_wire_protocol.py
We decided to strengthen the query stats contract in the driver.
Implement QueryStats class.
* Add and fix tests
----
> Strengthen query stats contract

- concourse/scripts/build.sh
- concourse/scripts/publish.sh
- concourse/scripts/publish_docs.sh
- tests/run-tests.sh
Fix the `set` in our shell scripts
> Correct set options

- tests/run-tests.sh
Noticed we had a few shcheck warnings
Cleaned them up 
shcheck happy
Run the docker compose suite locally
----
> shellcheck fixes

- fauna/__init__.py
Increment version to 0.2.0
----
> Incr to version 0.2.0

- concourse/scripts/publish_docs.sh
Mistakenly removed this chunk from the pipeline in #90 
Add it back 
Docs directory will be a git repo
None 🙈 
----
> Updated Publish Docs pipeline job

- concourse/scripts/publish_docs.sh
Need to diff staged content
----
> Updated Publish Docs pipeline job - attempt #2

- README.rst
We want to provide customers information about early access and standardize on the top of the driver READMEs across all FQL X drivers including links to the FQL X docs.
Update README.
Done
Previewed in GH.
----
> Updating README for early access

- README.rst
Readme examples should be simple and runnable.
Make them simple and runnable
Copy/pasted the examples and ran them
----
> Simpler readme examples

- concourse/pipeline.yml
We don't run our platform tests in the pipeline.
Add platform tests to pipeline.
Tested with a trial pipeline that excluded the release step. For internal reviewers, find `python-trial` in concourse.
----
> Add platform tests to pipeline

- concourse/pipeline.yml
Small errors in pipeline definition
----
> Small pipeline fix

- concourse/pipeline.yml
We have some params that were used in a previous iteration of platform tests.
Remove them.
----
> Remove unused task parameters

- fauna/query/models.py
- tests/unit/test_models.py
When you have a page, you should be able to loop through the content easily.
Add __iter__ to the Page object.
Added unit test.
----
> Add __iter__ to page for easy loops

- fauna/encoding/encoder.py
Something changed with the yapf github workflow. Local wants what's here, but the action wants something different.
Align with action for now and I'll resolve the local diff later.
----
> Fix YAPF error

- fauna/__init__.py
Release 0.6.1
* Add NullDocument support
* Add __iter__ to Page
* Fix error message for encoding failures
----
> Version 0.6.1

- README.rst
We don't yet support serialization and deserialization, and some are stubbing their toes on this.
Add a section to the readme that explains this.
Verified the example is valid code.
----
> Add serialization section to readme

- concourse/scripts/publish.sh
Notify driver watchers when new version released.
Tag in slack.
Watchers get notified
Need to do a release to really test
----
> Notify driver watchers when new version released

- fauna/__init__.py
Release 0.6.2
- Fixed #118 - `setup.py`: `python_requires`
> Version 0.6.2

- fauna/__init__.py
Bump the version to prepare for publishing to PyPI
----
> Prepare for 0.7.0 release

- tests/integration/test_query.py
Integration test is failing because the response message was updated on the backend.
Don't assert the value of the message, just that we got one.
Happy little tests 
PR Checks pass
----
> Updated integration test

- .github/workflows/validate-readme.yml
Ticket(s): BT-###, FE-###,...
We get burned by the README having minor formatting issues (see #141 ) and publishing is blocked
Add a basic workflow to validate the readme before we try to publish 
Catch errors early
Validated the workflow locally
----
> Validate Readme Workflow

- concourse/scripts/publish_docs.sh
Ticket(s): BT-4085
Didn't update the `rm` when we updated #135 
Corrected file path
Doc publishing will work 🤞 
None
----
> Fixed docs publishing

- fauna/__init__.py
Release throttling error retries.
----
> Bump to 1.1.0

- .github/workflows/build_and_test.yml
- README.rst
- setup.py
- tests/docker-compose-tests.yml
Include Python 3.12 in the supported versions list
----
> Python 3.12 Support

- CHANGELOG.md
- fauna/__init__.py
Release 1.1.1
* Fix bug in circular reference detection https://github.com/fauna/fauna-python/issues/154
----
> Release 1.1.1

- fauna/client/client.py
- tests/integration/test_stream.py
- tests/unit/test_client.py
ENG-6086
This pr allow users to opt-in for handling status events.
> Add option for user to handle status events

- concourse/pipeline.yml
Ticket(s): BT-###, FE-###,...
Explain the context and why you're making that change. What is the problem you're trying to solve? In some cases there is not a problem and this can be thought of being the motivation for your change.
Describe the modifications you've done.
Describe the manual and automated tests you completed to verify the change is working as expected.
----
> Add beta pipeline

- fauna/__init__.py
> Release 1.2.0b1

- fauna/__init__.py
- fauna/client/client.py
- tests/integration/test_stream.py
> Release 1.2.0b2

- fauna/__init__.py
> Release 1.2.0.b3

- README.md
Update readme installation instructions.
----
> Update beta readme install

- fauna/__init__.py
> Release 1.2.0b4

- fauna/client/client.py
- fauna/client/retryable.py
- fauna/encoding/encoder.py
- fauna/errors/__init__.py
- fauna/http/http_client.py
- fauna/http/httpx_client.py
- fauna/query/__init__.py
- fauna/query/template.py
- tests/integration/test_client.py
- tests/integration/test_client_with_query_limits.py
- tests/integration/test_data_type_roundtrips.py
- tests/integration/test_query.py
- tests/integration/test_stream.py
- tests/unit/test_client.py
- tests/unit/test_encoding.py
- tests/unit/test_httpx_client.py
- tests/unit/test_models.py
- tests/unit/test_retryable.py
Imports are a bit messy
Clean them up
None
----
> Run optimize imports everywhere

- fauna/__init__.py
Ticket(s): BT-4856
Release version 2.0.0
* Add streaming support
* Add `@bytes` support
----
> Release 2.0.0

- .github/PULL_REQUEST_TEMPLATE.md
* Update the PR template to this one
* Alignment across our v10 repos
----
> Align PR template

- fauna/__init__.py
> Release 2.1.0

- .github/workflows/build_and_test.yml
- README.md
- fauna/client/client.py
- tests/integration/test_stream.py
- tests/unit/test_client.py
Provide support for the new per-event stream cursor.
There's an edge case where resuming a stream from a txn time with lots of documents written could result in event loss. This approach fixes that edge case.
Unit tests included.
NA
* - [X] Bug fix (non-breaking change that fixes an issue)
* - [X] New feature (non-breaking change that adds functionality)
* - [X] My change requires a change to Fauna documentation.
* - [X] My change requires a change to the README, and I have updated it accordingly.
----
> ENG-6607: Introduce support for event cursors

- README.md
Updates the streaming examples to align with the new sample data.
----
> [DOCS-3454] README: Update streaming sample data

- fauna/__init__.py
> Release 2.3.0

- requirements.txt
Update HTTPX dependency to a newer version
Solve for #205 
Cutting the PR to let tests run 
* - [x] New feature (non-breaking change that adds functionality)
* - [x] My code follows the code style of this project.
----
> feat: Bump httpx version

- fauna/__init__.py
> Release 2.4.0
